name: Update Language Stats

on:
  schedule:
    - cron: "0 0 * * 1" # every Monday
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install matplotlib requests

      - name: Run Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python generate_lang_stats.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md lang_stats.png
          git commit -m "Update language stats" || echo "No changes"
          git push
